import pyautogui
import time
import datetime
pyautogui.PAUSE = 0.6

time.sleep(10)
pyautogui.press('win')
pyautogui.write("C d A d T R")
time.sleep(3)
pyautogui.press('enter')
time.sleep(5)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('enter')
time.sleep(4)
#pyautogui.click(x=25, y=358)
#pyautogui.doubleClickpress()
#pyautogui.doubleClick(x=30, y=360)

#pyautogui.press('win')
time.sleep(4)
#pyautogui.write("RApp-@ C")
#time.sleep(3)
#pyautogui.press('enter')
#pyautogui.doubleClick(x=36, y=337)
pyautogui.doubleClick(x=26, y=362)
time.sleep(3)
pyautogui.hotkey('shift', 'tab')
pyautogui.press('enter')
time.sleep(6)
#pyautogui.write("LOL@2000")
#pyautogui.write("LOL")
#time.sleep(6)
#pyautogui.hotkey('shift', '2')
#time.sleep(5)
#pyautogui.write("2000")
#time.sleep(6)
#pyautogui.press('tab')
#pyautogui.press('tab')
pyautogui.press('capslock')
time.sleep(2)
pyautogui.press('l')
time.sleep(1)
pyautogui.press('o')
time.sleep(1)
pyautogui.press('l')
time.sleep(1)
pyautogui.press('capslock')
time.sleep(1)
pyautogui.hotkey('shift', '2')
time.sleep(1)
pyautogui.press('2')
time.sleep(1)
pyautogui.press('0')
time.sleep(1)
pyautogui.press('0')
time.sleep(1)
pyautogui.press('0')
time.sleep(3)
pyautogui.press('enter')
time.sleep(5)
pyautogui.hotkey('shift', 'tab')
pyautogui.press('enter')
#time.sleep(7)
#pyautogui.hotkey('shift', 'tab')
time.sleep(5)
pyautogui.click(x=716, y=454)
pyautogui.hotkey('ctrl', 'a')
time.sleep(5)
pyautogui.write("name")
time.sleep(4)
pyautogui.press('tab')
pyautogui.write("###")
time.sleep(4)
pyautogui.press('tab')
pyautogui.press('enter')
time.sleep(6)
#19tabs
pyautogui.click(x=79, y=399)
#for _ in range(18):
#    pyautogui.press('tab')
time.sleep(5)
pyautogui.press('enter')
time.sleep(5)
#pyautogui.press('enter')
#time.sleep(3)
#pyautogui.press('alt')
time.sleep(2)
#pyautogui.hotkey('ctrl', 'right')
#pyautogui.hotkey('ctrl', 'right')
#pyautogui.press('enter')
pyautogui.click(x=164, y=34)
time.sleep(5)
pyautogui.click(x=239, y=302)
#for _ in range(10):
#    pyautogui.hotkey('ctrl', 'down')
#pyautogui.press('enter')
time.sleep(5)
pyautogui.click(x=150, y=83)
time.sleep(4)
pyautogui.press('a')
pyautogui.press('backspace')
time.sleep(3)
#pyautogui.hotkey('down')
#pyautogui.press('enter')
pyautogui.doubleClick(x=245, y=121)
time.sleep(4)
pyautogui.write("01/01/2024")
time.sleep(3)
pyautogui.press('enter')
data_atual = datetime.datetime.now().strftime("%d/%m/%y")
time.sleep(3)
pyautogui.write(data_atual)
time.sleep(3)
pyautogui.press('enter')
time.sleep(3)
#time.sleep(3)
#pyautogui.press('tab')
#time.sleep(1)
#pyautogui.press('tab')
#time.sleep(1)
#pyautogui.press('tab')
#time.sleep(1)
#pyautogui.press('enter')
pyautogui.click(x=1181, y=96)
time.sleep(55)
#for _ in range(6):
#    pyautogui.press('tab')
#time.sleep(2)
#pyautogui.press('enter')
pyautogui.click(x=372, y=425)
time.sleep(70)
#pyautogui.hotkey('alt', 'tab')

time.sleep(15)
pyautogui.click(x=376, y=876)
time.sleep(6)
pyautogui.click(x=36, y=197)
time.sleep(5)
pyautogui.press('tab')
pyautogui.hotkey('shift', 'tab')
time.sleep(2)
#pyautogui.hotkey('ctrl', 'shift', 'right')
pyautogui.keyDown('shift')
time.sleep(3)
pyautogui.hotkey('ctrl', 'right')
time.sleep(3)
pyautogui.hotkey('ctrl', 'down')
time.sleep(3)
pyautogui.keyUp('shift')
#pyautogui.hotkey('ctrl', 'shift', 'down')
time.sleep(6)
pyautogui.hotkey('ctrl', 'c')
time.sleep(7)
pyautogui.press('win')
time.sleep(7)
pyautogui.write("Excel")
time.sleep(6)
pyautogui.press('enter')
time.sleep(7)
pyautogui.press('enter')
time.sleep(5)
pyautogui.hotkey('ctrl', 'v')
time.sleep(4)
pyautogui.hotkey('ctrl', 'down')
time.sleep(4)
pyautogui.press('down')

time.sleep(4)
pyautogui.keyDown('alt')
pyautogui.press('tab')
pyautogui.press('right')
pyautogui.keyUp('alt')

#time.sleep(14)
time.sleep(2)
for _ in range(12):
    pyautogui.hotkey('shift', 'tab')
pyautogui.press('backspace')

time.sleep(3)
pyautogui.doubleClick(x=234, y=165)
#for _ in range(4):
    #pyautogui.hotkey('ctrl', 'down')
#    pyautogui.press('down')
#    time.sleep(2)
#pyautogui.press('enter')

time.sleep(4)
for _ in range(5):
    pyautogui.press('tab')
pyautogui.press('enter')

time.sleep(50)
pyautogui.keyDown('alt')
pyautogui.press('tab')
pyautogui.press('right')
pyautogui.keyUp('alt')

time.sleep(10)
#pyautogui.hotkey('alt', 'f4')
#pyautogui.hotkey('alt', 'f4')
pyautogui.click(x=1407, y=0)
time.sleep(3)
#pyautogui.click(x=644, y=493)
#pyautogui.hotkey('shift', 'tab')
pyautogui.click(x=728, y=487)
time.sleep(2)
pyautogui.click(x=732, y=501)
#pyautogui.press('enter')
time.sleep(2)
pyautogui.click(x=304, y=881)

time.sleep(8)
for _ in range(6):
    pyautogui.press('tab')
pyautogui.press('enter')

time.sleep(90)
pyautogui.click(x=359, y=867)

#pyautogui.keyDown('alt')
#pyautogui.press('tab')
#pyautogui.press('right')
#pyautogui.keyUp('alt')
time.sleep(6)
pyautogui.click(x=36, y=197)
time.sleep(7)
pyautogui.press('down')
time.sleep(3)
#pyautogui.hotkey('ctrl', 'shift', 'right')
#pyautogui.hotkey('ctrl', 'shift', 'down')
pyautogui.keyDown('shift')
time.sleep(3)
pyautogui.hotkey('ctrl', 'right')
time.sleep(3)
pyautogui.hotkey('ctrl', 'down')
time.sleep(3)
pyautogui.keyUp('shift')
time.sleep(5)
pyautogui.hotkey('ctrl', 'c')
time.sleep(5)
pyautogui.click(x=210, y=885)
#pyautogui.keyDown('alt')
#pyautogui.press('tab')
#pyautogui.press('right')
#pyautogui.keyUp('alt')
time.sleep(3)
pyautogui.hotkey('ctrl', 'v')
time.sleep(3)
#pyautogui.hotkey('ctrl', 'down')
pyautogui.press('down')
time.sleep(2)
pyautogui.press('alt')
time.sleep(2)
pyautogui.press('a')
time.sleep(2)
pyautogui.press('a')

pyautogui.click(x=257, y=463)
time.sleep(4)
pyautogui.click(x=114, y=164)
time.sleep(4)
pyautogui.click(x=426, y=45)
time.sleep(5)
pyautogui.hotkey('ctrl', 'a')
time.sleep(4)
pyautogui.press('backspace')
time.sleep(4)
#Path
#pyautogui.write("\\#\#\##\###")
pyautogui.write("\#")
time.sleep(4)
pyautogui.press('backspace')
time.sleep(4)
pyautogui.write("\#\#\##\###")
time.sleep(3)
pyautogui.press('enter')
#pyautogui.press('y')
#pyautogui.press('4')
time.sleep(3)
pyautogui.click(x=281, y=348)
time.sleep(6)
pyautogui.write("name file to update")
time.sleep(7)
for _ in range(7):
    pyautogui.press('tab')
    time.sleep(2)
pyautogui.press('enter')
time.sleep(6)
pyautogui.hotkey('shift', 'tab')
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.hotkey('alt', 'f4')
time.sleep(10)
pyautogui.click(x=1407, y=0)
#pyautogui.hotkey('alt', 'f4')
#pyautogui.hotkey('alt', 'f4')
time.sleep(10)
pyautogui.click(x=713, y=495)
#pyautogui.hotkey('shift', 'tab')
#pyautogui.press('enter')
time.sleep(6)
pyautogui.click(x=1423, y=4)
time.sleep(10)
pyautogui.click(x=733, y=490)
#pyautogui.click(x=732, y=501)

time.sleep(10)
pyautogui.click(x=1418, y=12)
pyautogui.click(x=1414, y=0)
#pyautogui.hotkey('alt', 'f4')
time.sleep(10)
pyautogui.click(x=1414, y=7)
time.sleep(10)
pyautogui.click(x=779, y=505)
#pyautogui.hotkey('alt', 'f4')

#pyautogui.hotkey('shift', 'tab')
#pyautogui.press('enter')
time.sleep(8)
pyautogui.click(x=1028, y=13)
time.sleep(4)
pyautogui.press('enter')
