import pyautogui
import time
import datetime
pyautogui.PAUSE = 0.6

time.sleep(10)
pyautogui.press('win')
pyautogui.write("C d A d T R")
time.sleep(3)
pyautogui.press('enter')
time.sleep(5)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('enter')
time.sleep(4)
#pyautogui.click(x=25, y=358)
#pyautogui.doubleClickpress()
#pyautogui.doubleClick(x=30, y=360)

#pyautogui.press('win')
time.sleep(4)
#pyautogui.write("RApp-@ C")
#time.sleep(3)
#pyautogui.press('enter')
#pyautogui.doubleClick(x=36, y=337)
pyautogui.doubleClick(x=26, y=362)
time.sleep(3)
pyautogui.hotkey('shift', 'tab')
pyautogui.press('enter')
time.sleep(6)
#pyautogui.write("LOL@2000")
#pyautogui.write("LOL")
#time.sleep(6)
#pyautogui.hotkey('shift', '2')
#time.sleep(5)
#pyautogui.write("2000")
#time.sleep(6)
#pyautogui.press('tab')
#pyautogui.press('tab')
pyautogui.press('capslock')
time.sleep(2)
pyautogui.press('l')
time.sleep(1)
pyautogui.press('o')
time.sleep(1)
pyautogui.press('l')
time.sleep(1)
pyautogui.press('capslock')
time.sleep(1)
pyautogui.hotkey('shift', '2')
time.sleep(1)
pyautogui.press('2')
time.sleep(1)
pyautogui.press('0')
time.sleep(1)
pyautogui.press('0')
time.sleep(1)
pyautogui.press('0')
time.sleep(3)
pyautogui.press('enter')
time.sleep(5)
pyautogui.hotkey('shift', 'tab')
pyautogui.press('enter')
#time.sleep(7)
#pyautogui.hotkey('shift', 'tab')
time.sleep(5)
pyautogui.click(x=716, y=454)
pyautogui.hotkey('ctrl', 'a')
time.sleep(5)
pyautogui.write("name")
time.sleep(4)
pyautogui.press('tab')
pyautogui.write("###")
time.sleep(4)
pyautogui.press('tab')
pyautogui.press('enter')
time.sleep(6)
#19tabs
pyautogui.click(x=79, y=399)
#for _ in range(18):
#    pyautogui.press('tab')
time.sleep(5)
pyautogui.press('enter')
time.sleep(5)
pyautogui.click(x=164, y=34)
time.sleep(5)
#pyautogui.click(x=253, y=470)
pyautogui.click(x=283, y=459)
time.sleep(5)
#pyautogui.click(x=147, y=149)
pyautogui.click(x=138, y=147)
time.sleep(5)
pyautogui.write("01/03/2025")
time.sleep(5)
pyautogui.press('tab')
time.sleep(6)
data_atual = datetime.datetime.now().strftime("%d/%m/%y")
time.sleep(3)
pyautogui.write(data_atual)
time.sleep(4)
pyautogui.press("enter")
time.sleep(5)
pyautogui.click(x=1257, y=138)
time.sleep(5)
pyautogui.click(x=647, y=583)
time.sleep(4)
pyautogui.click(x=624, y=602)
time.sleep(5)
pyautogui.click(x=701, y=584)
time.sleep(40)
pyautogui.click(x=376, y=876)
time.sleep(6)
pyautogui.click(x=36, y=197)
time.sleep(5)
pyautogui.press('tab')
pyautogui.hotkey('shift', 'tab')
time.sleep(2)
#pyautogui.hotkey('ctrl', 'shift', 'right')
pyautogui.keyDown('shift')
time.sleep(3)
pyautogui.hotkey('ctrl', 'right')
time.sleep(3)
pyautogui.hotkey('ctrl', 'down')
time.sleep(3)
pyautogui.keyUp('shift')
#pyautogui.hotkey('ctrl', 'shift', 'down')
time.sleep(6)
pyautogui.hotkey('ctrl', 'c')
time.sleep(7)
pyautogui.press('win')
time.sleep(7)
pyautogui.write("Excel")
time.sleep(6)
pyautogui.press('enter')
time.sleep(7)
pyautogui.press('enter')
time.sleep(5)
pyautogui.hotkey('ctrl', 'v')
time.sleep(4)
pyautogui.hotkey('ctrl', 'down')
time.sleep(4)
pyautogui.press('down')
time.sleep(4)
pyautogui.press('alt')
time.sleep(2)
pyautogui.press('a')
time.sleep(2)
pyautogui.press('a')
time.sleep(4)
pyautogui.click(x=257, y=463)
time.sleep(4)
pyautogui.click(x=114, y=164)
time.sleep(4)
pyautogui.click(x=426, y=45)
time.sleep(5)
pyautogui.hotkey('ctrl', 'a')
time.sleep(4)
pyautogui.press('backspace')
time.sleep(4)
#pyautogui.write("\\#\#\##\###")
pyautogui.write("\#")
time.sleep(4)
pyautogui.press('backspace')
time.sleep(4)
pyautogui.write("\#\#\##\###")
time.sleep(3)
pyautogui.press('enter')
#pyautogui.press('y')
#pyautogui.press('4')
time.sleep(3)
pyautogui.click(x=281, y=348)
time.sleep(6)
pyautogui.write("nameFileToUpdate")
time.sleep(7)
for _ in range(7):
    pyautogui.press('tab')
    time.sleep(2)
pyautogui.press('enter')
time.sleep(6)
pyautogui.hotkey('shift', 'tab')
time.sleep(4)
pyautogui.press('enter')
time.sleep(4)
pyautogui.hotkey('alt', 'f4')
time.sleep(10)
pyautogui.click(x=1407, y=0)
time.sleep(10)
pyautogui.click(x=713, y=495)
#pyautogui.hotkey('shift', 'tab')
#pyautogui.press('enter')
time.sleep(6)
pyautogui.click(x=1423, y=4)
time.sleep(10)
pyautogui.click(x=733, y=490)
#pyautogui.click(x=732, y=501)

time.sleep(10)
pyautogui.click(x=1418, y=12)
pyautogui.click(x=1414, y=0)
#pyautogui.hotkey('alt', 'f4')
time.sleep(10)
pyautogui.click(x=1414, y=7)
time.sleep(10)
pyautogui.click(x=779, y=505)
#pyautogui.hotkey('alt', 'f4')

#pyautogui.hotkey('shift', 'tab')
#pyautogui.press('enter')
time.sleep(8)
pyautogui.click(x=1028, y=13)
time.sleep(4)
pyautogui.press('enter')
